version: "3"


services:
  tracker_db:
    container_name: tracker_db
    restart: always
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports: 
      - 27017
    volumes:
      - mongodb_data_container:/data/db
  redis_server:
    container_name: redis_server
    image: redis/redis-stack-server:latest
    expose:
      - 6379
    ports:
      - "6379:6379"
  tracker_backend:
    container_name: tracker_backend
    build: 
      context: .
    expose:
      - 4000
    env_file:
      ./.env
    environment:
      - NODE_ENV=production
      - DATABASE_URL=
    ports:
      - 4000:4000
    depends_on:
      - tracker_db
      - redis_server

volumes:
  mongodb_data_container: